cmake -B build/linux -S . -G "Ninja Multi-Config" \
  -DLY_UNITY_BUILD=OFF \
  -DLY_PARALLEL_LINK_JOBS=4 \
  -DLY_DISABLE_TEST_MODULES=FALSE \
  -DLY_STRIP_DEBUG_SYMBOLS=FALSE \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCONVERSATION_BUILD_DOCS=ON
